# Generated by Django 3.2.9 on 2021-11-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='StatisticModel',
        ),
    ]
